export const metadata = {
  title: "Terms of Service — ResumeAI",
  description: "The terms that govern your use of ResumeAI.",
};

const SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body: [
      "By creating an account or using ResumeAI (the \u201cService\u201d), you agree to these Terms of Service. If you do not agree, please do not use the Service.",
    ],
  },
  {
    heading: "2. The Service",
    body: [
      "ResumeAI helps you create, tailor, and export resumes and cover letters using AI. Features available to you depend on your plan (Free or Pro) and associated usage credits.",
    ],
  },
  {
    heading: "3. Accounts",
    body: [
      "You must provide a valid email address to sign in via one-time passcodes. You are responsible for maintaining access to your email account and for all activity under your account. You must be at least 13 years old to use the Service.",
    ],
  },
  {
    heading: "4. Acceptable Use",
    body: [
      "You agree not to misuse the Service, including: attempting to access other users\u2019 data; circumventing credit limits or permission controls; uploading malicious files or content you do not have rights to; or using the Service to violate any applicable law.",
      "You confirm that resume content you upload is accurate and belongs to you.",
    ],
  },
  {
    heading: "5. Subscriptions & Payments",
    body: [
      "Paid plans renew automatically each billing interval until cancelled and are processed by Stripe. Applicable taxes may apply. You can manage or cancel your subscription at any time from your profile page; cancellation takes effect per the Stripe subscription terms, and access continues until the end of the paid period.",
      "Credits reset according to your plan (daily for Free, monthly for Pro) and do not roll over.",
    ],
  },
  {
    heading: "6. Refunds",
    body: [
      "Subscription payments are generally non-refundable, except where required by law. Contact support if you believe a charge was made in error.",
    ],
  },
  {
    heading: "7. AI-Generated Content",
    body: [
      "Content generated by the Service is provided \u201cas is.\u201d You are responsible for reviewing its accuracy before sending it to employers. We do not guarantee job interviews or employment outcomes.",
      "You own the resumes and cover letters you create with the Service.",
    ],
  },
  {
    heading: "8. Intellectual Property",
    body: [
      "All software, templates, branding, and content comprising the Service remain the property of ResumeAI. Nothing in these terms transfers ownership of the Service to you.",
    ],
  },
  {
    heading: "9. Termination",
    body: [
      "We may suspend or terminate accounts that violate these terms. You may stop using the Service at any time and request deletion of your data.",
    ],
  },
  {
    heading: "10. Disclaimers & Liability",
    body: [
      "THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, RESUMEAI SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.",
    ],
  },
  {
    heading: "11. Changes to These Terms",
    body: [
      "We may update these terms from time to time. Material changes will be communicated through the Service. Continued use after changes take effect constitutes acceptance.",
    ],
  },
  {
    heading: "12. Contact",
    body: ["Questions about these terms? Contact us at support@resumeai.app."],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen py-20">
      <div className="container mx-auto px-6 max-w-3xl">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: August 21, 2026</p>

        <div className="space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="text-xl font-bold mb-3 text-white">{s.heading}</h2>
              <div className="space-y-3">
                {s.body.map((p, i) => (
                  <p key={i} className="text-slate-400 leading-relaxed">{p}</p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
